from pathlib import Path
p=Path('src/Presentation/Admin/ProductionAdmin.php')
s=p.read_text()
needle="<tr><th>情報解禁</th><td><input type=\"datetime-local\" name=\"performance_release\" value=\"'.esc_attr($this->jst($g('performance_release'))).'\" /></td></tr><tr><th>ラベル</th>"
insert="<tr><th>情報解禁</th><td><input type=\"datetime-local\" name=\"performance_release\" value=\"'.esc_attr($this->jst($g('performance_release'))).'\" /></td></tr><tr><th>表示方式</th><td><select name=\"performance_view\"><option value=\"table\" '.selected($g('performance_view','table'),'table',false).'>表形式</option><option value=\"list\" '.selected($g('performance_view'),'list',false).'>一覧形式</option><option value=\"timeline_line\" '.selected($g('performance_view'),'timeline_line',false).'>タイムライン（線）</option><option value=\"timeline_grid\" '.selected($g('performance_view'),'timeline_grid',false).'>タイムライン（区切り）</option></select></td></tr><tr><th>表示サイズ</th><td><label><input type=\"radio\" name=\"performance_size\" value=\"l\" '.checked($g('performance_size','l'),'l',false).'> L</label> <label><input type=\"radio\" name=\"performance_size\" value=\"m\" '.checked($g('performance_size','l'),'m',false).'> M</label> <label><input type=\"radio\" name=\"performance_size\" value=\"s\" '.checked($g('performance_size','l'),'s',false).'> S</label></td></tr><tr><th>ラベル</th>"
if needle not in s: raise SystemExit('performance UI anchor missing')
s=s.replace(needle,insert,1)
needle="<tr><th>情報解禁</th><td><input type=\"datetime-local\" name=\"ticket_release\" value=\"'.esc_attr($this->jst($g('ticket_release'))).'\" /></td></tr><tr><th>税表示</th>"
insert="<tr><th>表示サイズ</th><td><label><input type=\"radio\" name=\"ticket_size\" value=\"l\" '.checked($g('ticket_size','l'),'l',false).'> L</label> <label><input type=\"radio\" name=\"ticket_size\" value=\"m\" '.checked($g('ticket_size','l'),'m',false).'> M</label> <label><input type=\"radio\" name=\"ticket_size\" value=\"s\" '.checked($g('ticket_size','l'),'s',false).'> S</label></td></tr><tr><th>情報解禁</th><td><input type=\"datetime-local\" name=\"ticket_release\" value=\"'.esc_attr($this->jst($g('ticket_release'))).'\" /></td></tr><tr><th>税表示</th>"
if needle not in s: raise SystemExit('ticket UI anchor missing')
s=s.replace(needle,insert,1)
needle="private function cleanRows(array$rows):array{$out=[];foreach($rows as$r){if(!is_array($r))continue;$x=[];foreach($r as$k=>$v)$x[$k]=is_string($v)?sanitize_text_field(wp_unslash($v)):$v;$out[]=$x;}return$out;}"
insert="private function cleanRows(array$rows):array{$out=[];foreach($rows as$rowKey=>$r){if(!is_array($r))continue;$x=[];foreach($r as$k=>$v)$x[$k]=is_string($v)?sanitize_text_field(wp_unslash($v)):$v;$out[$rowKey]=$x;}return$out;}"
if needle not in s: raise SystemExit('cleanRows anchor missing')
s=s.replace(needle,insert,1)
needle="update_post_meta($id,'legend',in_array($_POST['legend']??'none',['none','above','below'],true)?$_POST['legend']:'none');$labelRows=$this->cleanRows($_POST['labels']??[]);$this->repo->saveLabels($id,$labelRows);$performanceRows=$this->cleanRows($_POST['performances']??[]);$this->repo->savePerformances($id,$performanceRows);"
insert="update_post_meta($id,'legend',in_array($_POST['legend']??'none',['none','above','below'],true)?$_POST['legend']:'none');$performanceView=sanitize_key(wp_unslash($_POST['performance_view']??'table'));if(!in_array($performanceView,['table','list','timeline_line','timeline_grid'],true))$performanceView='table';update_post_meta($id,'performance_view',$performanceView);$performanceSize=sanitize_key(wp_unslash($_POST['performance_size']??'l'));if(!in_array($performanceSize,['l','m','s'],true))$performanceSize='l';update_post_meta($id,'performance_size',$performanceSize);$ticketSize=sanitize_key(wp_unslash($_POST['ticket_size']??'l'));if(!in_array($ticketSize,['l','m','s'],true))$ticketSize='l';update_post_meta($id,'ticket_size',$ticketSize);$labelRows=$this->cleanRows($_POST['labels']??[]);$labelIds=$this->repo->saveLabels($id,$labelRows,(array)($_POST['deleted_labels']??[]));$performanceRows=$this->cleanRows($_POST['performances']??[]);foreach($performanceRows as&$performanceRow){$labelKey=(string)($performanceRow['label_id']??'');if($labelKey!==''&&!ctype_digit($labelKey)&&isset($labelIds[$labelKey]))$performanceRow['label_id']=$labelIds[$labelKey];}unset($performanceRow);$this->repo->savePerformances($id,$performanceRows);"
if needle not in s: raise SystemExit('save anchor missing')
s=s.replace(needle,insert,1)
s=s.replace('<h3>公演スケジュールラベル</h3><table class=\"widefat\" id=\"sa-labels\">','<h3>公演スケジュールラベル</h3><div id=\"sa-label-deletions\"></div><table class=\"widefat\" id=\"sa-labels\">',1)
needle="const tr=remove.closest('tr'),label=tr.closest('#sa-labels');if(label){tr.remove();}"
if needle in s:
    s=s.replace(needle,"const tr=remove.closest('tr'),label=tr.closest('#sa-labels');if(label){const id=tr.querySelector('input[name*=\"[id]\"]')?.value||'';if(id){document.getElementById('sa-label-deletions')?.insertAdjacentHTML('beforeend','<input type=\"hidden\" name=\"deleted_labels[]\" value=\"'+id+'\">');}tr.remove();}",1)
p.write_text(s)
