<?php

declare(strict_types=1);
namespace StageArtCore\Presentation\Admin;
use StageArtCore\Presentation\PublicSite\ProductionLayout;
final class ProductionLayoutAdmin{
 public function register():void{add_action('admin_footer',[$this,'footer']);add_action('save_post_stageart_production',[$this,'save'],20,3);}
 public function footer():void{
  if(($_GET['page']??'')!=='stageart-productions'||!current_user_can('manage_options'))return;
  $rows=ProductionLayout::get((int)($_GET['id']??0));
  echo'<style>.stageart-layout-box{margin:20px 0;padding:16px;background:#fff;border:1px solid #ccd0d4}.stageart-layout-row{display:flex;align-items:center;gap:12px;padding:9px;margin:4px 0;background:#f6f7f7;border:1px solid #dcdcde;cursor:move}.stageart-layout-row label{margin-left:auto}.stageart-layout-row label+label{margin-left:0}.stageart-layout-row select{min-width:70px}</style>';
  echo'<script>(function(){const f=document.getElementById("stageart-production-form");if(!f)return;const rows='.wp_json_encode($rows,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).';const box=document.createElement("div");box.className="stageart-layout-box";const h=document.createElement("h2");h.textContent="トップ画面・コンテンツ配置";box.appendChild(h);const p=document.createElement("p");p.textContent="この公演ページだけの表示順・表示/非表示を設定できます。公演データそのものは変更されません。";box.appendChild(p);const wrap=document.createElement("div");box.appendChild(wrap);const hidden=document.createElement("input");hidden.type="hidden";hidden.name="stageart_production_layout";hidden.id="stageart-production-layout-json";box.appendChild(hidden);const nonce=document.createElement("input");nonce.type="hidden";nonce.name="stageart_production_layout_nonce";nonce.value='.wp_json_encode(wp_create_nonce('stageart_production_layout')).';box.appendChild(nonce);function sync(){hidden.value=JSON.stringify(rows)}function draw(){wrap.innerHTML="";rows.forEach(function(r,i){const row=document.createElement("div");row.className="stageart-layout-row";row.draggable=true;row.dataset.i=i;const grip=document.createElement("span");grip.textContent="☰";const name=document.createElement("strong");name.textContent=r.label;const en=document.createElement("label");const cb=document.createElement("input");cb.type="checkbox";cb.checked=!!r.enabled;en.append(cb," 表示");row.append(grip,name,en);row.addEventListener("dragstart",e=>e.dataTransfer.setData("text/plain",String(i)));row.addEventListener("dragover",e=>e.preventDefault());row.addEventListener("drop",e=>{e.preventDefault();const from=Number(e.dataTransfer.getData("text/plain")),to=Number(row.dataset.i);if(from===to)return;const x=rows.splice(from,1)[0];rows.splice(to,0,x);draw();sync()});cb.addEventListener("change",()=>{r.enabled=cb.checked;sync()});wrap.appendChild(row)})}draw();sync();const submit=f.querySelector("button[type=submit]");if(submit)f.insertBefore(box,submit.closest("p")||null)})()</script>';
 }
 public function save(int$postId,\WP_Post$post,bool$update):void{if((defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)||!current_user_can('manage_options')||$post->post_type!=='stageart_production')return;$nonce=isset($_POST['stageart_production_layout_nonce'])?sanitize_text_field(wp_unslash($_POST['stageart_production_layout_nonce'])):'';if(!$nonce||!wp_verify_nonce($nonce,'stageart_production_layout'))return;$raw=isset($_POST['stageart_production_layout'])?json_decode(wp_unslash((string)$_POST['stageart_production_layout']),true):[];if(is_array($raw))ProductionLayout::save($postId,$raw);}
}
