<?php
declare(strict_types=1);
namespace StageArtCore\Presentation\Admin;
use StageArtCore\Domain\Production\ProductionRepository;
use StageArtCore\Domain\Ticket\TicketRepository;
final class TicketAdmin{
 private TicketRepository $t;private ProductionRepository $p;
 public function __construct(){$this->t=new TicketRepository();$this->p=new ProductionRepository();add_action('admin_post_stageart_ticket_capacity',[$this,'capacity']);add_action('admin_post_stageart_ticket_checkin',[$this,'checkin']);add_action('admin_post_stageart_ticket_checkin_cancel',[$this,'checkinCancel']);add_action('admin_post_stageart_ticket_qr_checkin',[$this,'qrCheckin']);add_action('admin_post_stageart_ticket_sales',[$this,'sales']);add_action('admin_post_stageart_ticket_door',[$this,'door']);}
 public function register():void{add_submenu_page('stageart-plugin','チケット管理','チケット管理','manage_options','stageart-tickets',[$this,'render']);add_submenu_page('stageart-plugin','QR受付','QR受付','manage_options','stageart-ticket-scan',[$this,'scanner']);}
 public function render():void{$pid=(int)($_GET['production_id']??0);$performance=(int)($_GET['performance_id']??0);$posts=get_posts(['post_type'=>'stageart_production','post_status'=>['publish','draft'],'numberposts'=>-1,'orderby'=>'date','order'=>'DESC']);echo'<div class="wrap"><h1>チケット管理</h1><form method="get"><input type="hidden" name="page" value="stageart-tickets"><select name="production_id"><option value="">公演を選択</option>';foreach($posts as$p)echo'<option value="'.(int)$p->ID.'" '.selected($pid,$p->ID,false).'>'.esc_html($p->post_title).'</option>';echo'</select> <button class="button">表示</button></form>';if(!$pid){echo'</div>';return;}$m=get_post_meta($pid);$start=(string)($m['ticket_sales_start_at'][0]??'');echo'<hr><h2>販売設定</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="stageart_ticket_sales"><input type="hidden" name="production_id" value="'.(int)$pid.'">'.wp_nonce_field('stageart_ticket_sales','_wpnonce',true,false).'<label>販売開始日時 <input type="datetime-local" name="ticket_sales_start_at" value="'.esc_attr($this->jst($start)).'"></label> <button class="button button-primary">保存</button><p class="description">販売終了は各公演日の0時です。予約画面には残席数を表示しません。</p></form><h2>公演回</h2><table class="widefat striped"><thead><tr><th>公演回</th><th>定員</th><th>予約</th><th>残席</th><th>来場</th><th>操作</th></tr></thead><tbody>';foreach($this->p->performances($pid)as$x){$r=$this->t->reservedQuantity((int)$x['id']);$c=$this->t->checkInCount((int)$x['id']);echo'<tr><td>'.esc_html($x['performance_date'].' '.substr((string)$x['start_time'],0,5)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="stageart_ticket_capacity"><input type="hidden" name="production_id" value="'.(int)$pid.'"><input type="hidden" name="performance_id" value="'.(int)$x['id'].'">'.wp_nonce_field('stageart_ticket_capacity','_wpnonce',true,false).'<input type="number" name="capacity" min="0" value="'.(int)$x['capacity'].'" style="width:90px"> <button class="button">保存</button></form></td><td>'.(int)$r.'人</td><td>'.max(0,(int)$x['capacity']-$r).'人</td><td>'.(int)$c.'人</td><td><a class="button" href="'.esc_url(admin_url('admin.php?page=stageart-tickets&production_id='.$pid.'&performance_id='.$x['id'])).'">受付</a></td></tr>';}echo'</tbody></table>';if($performance)$this->list($pid,$performance);echo'</div>';}
 public function scanner():void{
  if(!current_user_can('manage_options'))return;
  $selectedProduction=(int)($_GET['production_id']??0);
  $selectedPerformance=(int)($_GET['performance_id']??0);
  $lookup=trim(sanitize_text_field(wp_unslash($_GET['lookup']??'')));
  $done=!empty($_GET['done']);
  $posts=get_posts(['post_type'=>'stageart_production','post_status'=>['publish','draft'],'numberposts'=>-1,'orderby'=>'date','order'=>'DESC']);
  $found=null;
  if($lookup!==''){
    $key=$lookup;
    if(str_starts_with($key,'stageart-ticket:'))$key=substr($key,15);
    $found=$this->t->reservationByToken($key);
    if(!$found)$found=$this->t->reservationByNo($key);
  }
  $foundPerformance=$found?(int)$found['performance_id']:0;
  $foundProduction=$found?(int)$found['production_id']:0;
  $samePerformance=$found&&$selectedPerformance>0&&$foundPerformance===$selectedPerformance;
  $checked=$found&&!empty($found['checkin_id']);
  $selectedLabel='';
  foreach($posts as $pp){
    foreach($this->p->performances((int)$pp->ID) as $px){
      if((int)$px['id']===$selectedPerformance){
        $selectedLabel=$pp->post_title.' / '.$px['performance_date'].' '.substr((string)$px['start_time'],0,5);
      }
    }
  }
  $reserved=$selectedPerformance?$this->t->reservedQuantity($selectedPerformance):0;
  $arrived=$selectedPerformance?$this->t->checkInCount($selectedPerformance):0;
  echo'<div class="wrap stageart-ticket-scanner">';
  echo'<style>
  .stageart-ticket-scanner{max-width:900px}
  .stageart-scan-head{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}
  .stageart-scan-card{background:#fff;border:1px solid #dcdcde;border-radius:12px;padding:20px;margin:16px 0;box-shadow:0 1px 2px rgba(0,0,0,.04)}
  .stageart-scan-main{text-align:center;padding:28px 18px}
  .stageart-scan-frame{width:min(78vw,420px);aspect-ratio:1/1;margin:20px auto;border:4px solid #2271b1;border-radius:20px;display:flex;align-items:center;justify-content:center;color:#646970;background:#f6f7f7}
  .stageart-scan-frame video{width:100%;height:100%;object-fit:cover;border-radius:14px}
  .stageart-scan-big{font-size:1.1rem;padding:14px 22px!important;min-height:50px}
  .stageart-scan-result{font-size:1.05rem}
  .stageart-scan-result dt{font-weight:600;margin-top:12px}.stageart-scan-result dd{margin:3px 0 0;font-size:1.15rem}
  .stageart-scan-ok{border-left:5px solid #00a32a}.stageart-scan-warn{border-left:5px solid #dba617}.stageart-scan-error{border-left:5px solid #d63638}
  @media(max-width:782px){.stageart-ticket-scanner{margin:0 10px}.stageart-scan-card{padding:14px}.stageart-scan-frame{width:min(88vw,420px)}.stageart-scan-head h1{font-size:1.7rem}.stageart-scan-big{width:100%;font-size:1.05rem!important}.stageart-scan-result dd{font-size:1.2rem}}
  </style>';
  echo'<div class="stageart-scan-head"><h1>QR受付</h1><a class="button" href="'.esc_url(admin_url('admin.php?page=stageart-tickets&production_id='.$selectedProduction.'&performance_id='.$selectedPerformance)).'">チケット管理へ</a></div>';
  echo'<div class="stageart-scan-card"><h2>① 受付する公演回</h2><form method="get"><input type="hidden" name="page" value="stageart-ticket-scan"><select name="production_id" id="stageart-scan-production" class="stageart-scan-big" style="width:100%;max-width:650px"><option value="0">公演回を選択してください</option>';
  foreach($posts as $pp){
    $ps=$this->p->performances((int)$pp->ID);
    foreach($ps as $px){
      $label=$pp->post_title.' / '.$px['performance_date'].' '.substr((string)$px['start_time'],0,5);
      echo'<option value="'.(int)$pp->ID.'" data-performance="'.(int)$px['id'].'" '.selected($selectedPerformance,(int)$px['id'],false).'>'.esc_html($label).'</option>';
    }
  }
  echo'</select><input type="hidden" name="performance_id" id="stageart-scan-performance" value="'.(int)$selectedPerformance.'"><button class="button stageart-scan-big" style="margin-top:10px">この公演回で受付</button></form>';
  if($selectedPerformance)echo'<p><strong>現在受付：</strong>'.esc_html($selectedLabel).'　｜　受付済み '.(int)$arrived.' / '.(int)$reserved.'</p>';
  echo'</div>';
  if($done)echo'<div class="notice notice-success"><p><strong>チェックイン完了</strong>しました。</p></div>';
  if($selectedPerformance){
    echo'<div class="stageart-scan-card stageart-scan-main"><h2>② QRコードを読み取る</h2><div class="stageart-scan-frame" id="stageart-qr-frame">カメラを起動してください</div><p><button type="button" class="button button-primary stageart-scan-big" id="stageart-qr-start">📷 QRコードを読み取る</button> <button type="button" class="button stageart-scan-big" id="stageart-qr-stop">停止</button></p>';
    echo'<details><summary>QRが読み取れない場合</summary><form method="get" style="margin-top:16px"><input type="hidden" name="page" value="stageart-ticket-scan"><input type="hidden" name="production_id" value="'.(int)$selectedProduction.'"><input type="hidden" name="performance_id" value="'.(int)$selectedPerformance.'"><label>予約番号<br><input type="text" name="lookup" class="stageart-scan-big" style="width:100%;max-width:420px" placeholder="ST-20260929-0001" autocomplete="off"></label><br><button class="button button-primary stageart-scan-big" style="margin-top:10px">予約を検索</button></form></details></div>';
  }
  if($lookup!==''){
    if(!$found){
      echo'<div class="stageart-scan-card stageart-scan-error"><h2>予約が見つかりません</h2><p>QRコードまたは予約番号を確認してください。</p><a class="button" href="'.esc_url(add_query_arg(['page'=>'stageart-ticket-scan','production_id'=>$selectedProduction,'performance_id'=>$selectedPerformance],admin_url('admin.php'))).'">戻る</a></div>';
    }elseif(!$samePerformance){
      echo'<div class="stageart-scan-card stageart-scan-warn"><h2>⚠ 公演回が一致しません</h2><dl class="stageart-scan-result"><dt>予約</dt><dd>'.esc_html($found['reservation_no']).'</dd><dt>お名前</dt><dd>'.esc_html($found['customer_name']).' 様</dd><dt>予約枚数</dt><dd>'.(int)$found['quantity'].'枚</dd><dt>このQRの公演回</dt><dd>'.esc_html((string)$found['performance_id']).'</dd><dt>現在の受付</dt><dd>'.esc_html($selectedLabel).'</dd></dl><p><strong>この公演回ではチェックインできません。</strong></p><a class="button button-primary stageart-scan-big" href="'.esc_url(add_query_arg(['page'=>'stageart-ticket-scan','production_id'=>$foundProduction,'performance_id'=>$foundPerformance],admin_url('admin.php'))).'">この予約の公演回に切り替える</a></div>';
    }else{
      $pr=get_post($foundProduction);
      echo'<div class="stageart-scan-card '.($checked?'stageart-scan-warn':'stageart-scan-ok').'"><h2>'.($checked?'⚠ 受付済み':'③ 予約内容を確認').'</h2><dl class="stageart-scan-result"><dt>公演</dt><dd>'.esc_html($pr?$pr->post_title:'公演').'</dd><dt>予約番号</dt><dd><strong>'.esc_html($found['reservation_no']).'</strong></dd><dt>お名前</dt><dd>'.esc_html($found['customer_name']).' 様</dd><dt>枚数</dt><dd>'.(int)$found['quantity'].'枚</dd><dt>誰扱い</dt><dd>'.esc_html($this->attrs($foundProduction)[(int)($found['participant_id']??0)]['name']??'—').'</dd><dt>公演回ID</dt><dd>'.(int)$found['performance_id'].'</dd></dl>';
      if($checked){
        echo'<p><strong>チェックイン日時：</strong>'.esc_html((string)$found['checked_in_at']).'</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" onsubmit="return confirm(\'このチェックインを取り消しますか？\\n\\nOK：取り消す　CANCEL：やめる\')">'.wp_nonce_field('stageart_ticket_checkin_cancel','_wpnonce',true,false).'<input type="hidden" name="action" value="stageart_ticket_checkin_cancel"><input type="hidden" name="reservation_id" value="'.(int)$found['id'].'"><input type="hidden" name="production_id" value="'.(int)$selectedProduction.'"><input type="hidden" name="performance_id" value="'.(int)$selectedPerformance.'"><button class="button button-link-delete stageart-scan-big">チェックイン取消</button></form>';
      }else{
        echo'<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" onsubmit="return confirm(\'このお客様をチェックインしますか？\\n\\nOK：チェックイン　CANCEL：キャンセル\')">'.wp_nonce_field('stageart_ticket_qr_checkin','_wpnonce',true,false).'<input type="hidden" name="action" value="stageart_ticket_qr_checkin"><input type="hidden" name="reservation_id" value="'.(int)$found['id'].'"><input type="hidden" name="production_id" value="'.(int)$selectedProduction.'"><input type="hidden" name="performance_id" value="'.(int)$selectedPerformance.'"><button class="button button-primary stageart-scan-big">④ チェックイン</button></form>';
      }
      echo'</div>';
    }
  }
  if($selectedPerformance){
    echo'<div class="stageart-scan-card" style="text-align:center"><a class="button button-primary stageart-scan-big" href="'.esc_url(add_query_arg(['page'=>'stageart-ticket-scan','production_id'=>$selectedProduction,'performance_id'=>$selectedPerformance],admin_url('admin.php'))).'">次のお客様を受付</a></div>';
  }
  echo'<script>(function(){const sel=document.getElementById("stageart-scan-production"),perf=document.getElementById("stageart-scan-performance");if(sel&&perf){sel.addEventListener("change",function(){const o=this.options[this.selectedIndex];perf.value=o.dataset.performance||"0"})}const frame=document.getElementById("stageart-qr-frame"),start=document.getElementById("stageart-qr-start"),stop=document.getElementById("stageart-qr-stop");if(!frame||!start)return;let stream=null,raf=0;function stopCam(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(raf)cancelAnimationFrame(raf);raf=0}stop.onclick=stopCam;start.onclick=async function(){if(!("BarcodeDetector" in window)){alert("このブラウザはカメラQR読み取りに対応していません。下の「QRが読み取れない場合」から予約番号を入力してください。");return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}});frame.innerHTML="<video id=\"stageart-qr-video\" playsinline autoplay></video>";const v=document.getElementById("stageart-qr-video");v.srcObject=stream;await v.play();const detector=new BarcodeDetector({formats:["qr_code"]});const loop=async function(){if(!stream)return;try{const codes=await detector.detect(v);if(codes.length){let raw=String(codes[0].rawValue||"");if(raw.indexOf("stageart-ticket:")===0)raw=raw.substring(15);if(raw){stopCam();const u=new URL(window.location.href);u.searchParams.set("lookup",raw);window.location.href=u.toString();return}}}catch(e){}raf=requestAnimationFrame(loop)};loop()}catch(e){alert("カメラを起動できませんでした。ブラウザのカメラ権限とHTTPS接続を確認してください。")}};window.addEventListener("pagehide",stopCam)})();</script>';
  echo'</div>';
 } private function jst(string$v):string{if(!$v)return'';try{$d=new \DateTimeImmutable($v,new \DateTimeZone('UTC'));return$d->setTimezone(new \DateTimeZone('Asia/Tokyo'))->format('Y-m-d\\TH:i');}catch(\Throwable){return'';}}
 private function list(int$pid,int$performance):void{$rows=$this->t->reservations($performance);$attrs=$this->attrs($pid);echo'<h2>受付一覧</h2><p>「チェックイン」を押すと確認ダイアログが表示されます。OKで来場済みにし、CANCELで取り消せます。チェックイン後は「チェックイン取消」で元に戻せます。</p><p><button type="button" class="button button-primary" onclick="document.getElementById(\'stageart-door\').style.display=\'block\'">＋ 当日券を追加</button></p><div id="stageart-door" style="display:none"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('stageart_ticket_door','_wpnonce',true,false).'<input type="hidden" name="action" value="stageart_ticket_door"><input type="hidden" name="production_id" value="'.(int)$pid.'"><input type="hidden" name="performance_id" value="'.$performance.'"><label>誰扱い <select name="participant_id" required>';foreach($attrs as$a)echo'<option value="'.(int)$a['id'].'">'.esc_html($a['name']).'</option>';echo'</select></label> <label>枚数 <input type="number" name="quantity" min="1" required></label> <button class="button button-primary">OK</button></form></div><table class="widefat striped"><thead><tr><th>来場</th><th>予約番号</th><th>お名前</th><th>フリガナ</th><th>枚数</th><th>誰扱い</th><th>受付日時</th></tr></thead><tbody>';foreach($rows as$x){$checked=!empty($x['checkin_id']);echo'<tr><td>'.($checked?'<strong style="color:#2271b1">来場済み</strong> <form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="display:inline" onsubmit="return confirm(\'チェックインを取り消しますか？\\n\\nOK：取り消す　CANCEL：やめる\')"><input type="hidden" name="action" value="stageart_ticket_checkin_cancel"><input type="hidden" name="production_id" value="'.(int)$pid.'"><input type="hidden" name="performance_id" value="'.$performance.'"><input type="hidden" name="reservation_id" value="'.(int)$x['id'].'">'.wp_nonce_field('stageart_ticket_checkin_cancel','_wpnonce',true,false).'<button type="submit" class="button-link-delete">チェックイン取消</button></form>':'<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" onsubmit="return confirm(\'この予約をチェックインしますか？\\n\\nOK：チェックイン　CANCEL：キャンセル\')"><input type="hidden" name="action" value="stageart_ticket_checkin"><input type="hidden" name="production_id" value="'.(int)$pid.'"><input type="hidden" name="performance_id" value="'.$performance.'"><input type="hidden" name="reservation_id" value="'.(int)$x['id'].'">'.wp_nonce_field('stageart_ticket_checkin','_wpnonce',true,false).'<button type="submit" class="button">チェックイン</button></form>').'</td><td>'.esc_html($x['reservation_no']).'</td><td>'.esc_html($x['customer_name']).'</td><td>'.esc_html($x['customer_name_kana']).'</td><td>'.(int)$x['quantity'].'枚</td><td>'.esc_html($attrs[(int)($x['participant_id']??0)]['name']??'—').'</td><td>'.esc_html((string)($x['checked_in_at']??'')).'</td></tr>';}if(!$rows)echo'<tr><td colspan="7">予約はありません。</td></tr>';echo'</tbody></table>';}
 private function attrs(int$productionId):array{$a=[];foreach($this->p->participants($productionId)as$x){$participantId=(int)$x['id'];$name=trim((string)$x['name']);if($participantId>0&&$name!=='')$a[$participantId]=['id'=>$participantId,'name'=>$name];}return$a;}
 public function qrCheckin():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_qr_checkin');$id=(int)($_POST['reservation_id']??0);$x=$this->t->reservation($id);if(!$x)wp_die('有効な予約ではありません。');if(!empty($x['checkin_id']))wp_die('この予約はすでにチェックイン済みです。');$selected=(int)($_POST['performance_id']??0);if($selected>0&&(int)$x['performance_id']!==$selected)wp_die('受付する公演回が一致しません。');$this->t->checkIn($id,get_current_user_id());wp_safe_redirect(admin_url('admin.php?page=stageart-ticket-scan&production_id='.(int)$x['production_id'].'&performance_id='.(int)$x['performance_id'].'&done=1'));exit;}
 public function sales():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_sales');$pid=(int)$_POST['production_id'];$v=trim((string)($_POST['ticket_sales_start_at']??''));if($v==='')delete_post_meta($pid,'ticket_sales_start_at');else{$d=\DateTimeImmutable::createFromFormat('Y-m-d\\TH:i',$v,new \DateTimeZone('Asia/Tokyo'));if(!$d)wp_die('販売開始日時が正しくありません。');update_post_meta($pid,'ticket_sales_start_at',$d->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'));}wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;}
 public function capacity():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_capacity');$this->t->setCapacity((int)$_POST['performance_id'],max(0,(int)$_POST['capacity']));wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;}
 public function checkin():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_checkin');$this->t->checkIn((int)$_POST['reservation_id'],get_current_user_id());wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;} public function checkinCancel():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_checkin_cancel');$this->t->cancelCheckIn((int)$_POST['reservation_id']);wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;}
 public function door():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_door');$pid=(int)$_POST['production_id'];$perf=(int)$_POST['performance_id'];$uid=(int)$_POST['participant_id'];$qty=max(1,(int)$_POST['quantity']);if($qty>$this->t->capacity($perf)-$this->t->reservedQuantity($perf))wp_die('定員を超えるため登録できません。');$valid=false;foreach($this->attrs($pid)as$a)if($a['id']===$uid)$valid=true;if(!$valid)wp_die('誰扱いが不正です。');$this->t->doorReservation($pid,$perf,$uid,$qty);wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;}
}
